apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "horizon.openstack.org/v1beta1",
          "kind": "Horizon",
          "metadata": {
            "name": "horizon"
          },
          "spec": {
            "customServiceConfig": "DEBUG = True\nLOGGING['handlers']['console']['level'] = 'DEBUG'\n",
            "replicas": 1,
            "secret": "osp-secret"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-06-05T09:32:37Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: horizon-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Horizon is the Schema for the horizons API
        displayName: Horizon
        kind: Horizon
        name: horizons.horizon.openstack.org
        specDescriptors:
          - description: TLS - Parameters related to the TLS
            displayName: TLS
            path: tls
        version: v1beta1
  description: Horizon Operator
  displayName: Horizon Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - horizon.openstack.org
              resources:
                - horizons
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - horizon.openstack.org
              resources:
                - horizons/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - horizon.openstack.org
              resources:
                - horizons/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - k8s.cni.cncf.io
              resources:
                - network-attachment-definitions
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneapis
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneendpoints
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneservices
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - memcached.openstack.org
              resources:
                - memcacheds
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - anyuid
              resources:
                - securitycontextconstraints
              verbs:
                - use
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - hostmount-anyuid
              resources:
                - securitycontextconstraints
              verbs:
                - use
            - apiGroups:
                - topology.openstack.org
              resources:
                - topologies
              verbs:
                - get
                - list
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: horizon-operator-controller-manager
      deployments:
        - label:
            app.kubernetes.io/component: manager
            app.kubernetes.io/created-by: horizon-operator
            app.kubernetes.io/instance: controller-manager
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: deployment
            app.kubernetes.io/part-of: horizon-operator
            control-plane: controller-manager
            openstack.org/operator-name: horizon
          name: horizon-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                openstack.org/operator-name: horizon
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
                  openstack.org/operator-name: horizon
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/arch
                              operator: In
                              values:
                                - amd64
                                - arm64
                                - ppc64le
                                - s390x
                            - key: kubernetes.io/os
                              operator: In
                              values:
                                - linux
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    env:
                      - name: RELATED_IMAGE_HORIZON_IMAGE_URL_DEFAULT
                        value: quay.io/podified-antelope-centos9/openstack-horizon@sha256:e6c9a1da4097af58b05d41b0a964db7a17b9b6470c8cc8b49612954f573ff68f
                    image: quay.io/openstack-k8s-operators/horizon-operator@sha256:376fa11edc40f68251027f0f30f9e0db312cc88fd9386985b26e357f6e487515
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    ports:
                      - containerPort: 9443
                        name: webhook-server
                        protocol: TCP
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 256Mi
                      requests:
                        cpu: 10m
                        memory: 128Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    volumeMounts:
                      - mountPath: /tmp/k8s-webhook-server/serving-certs
                        name: cert
                        readOnly: true
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: horizon-operator-controller-manager
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: cert
                    secret:
                      defaultMode: 420
                      secretName: webhook-server-cert
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: horizon-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - OpenStack
    - UI
    - Horizon
  links:
    - name: Horizon Operator
      url: https://github.com/openstack-k8s-operators/horizon-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  relatedImages:
    - image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
      name: kube-rbac-proxy
    - image: quay.io/openstack-k8s-operators/horizon-operator@sha256:376fa11edc40f68251027f0f30f9e0db312cc88fd9386985b26e357f6e487515
      name: manager
    - image: quay.io/podified-antelope-centos9/openstack-horizon@sha256:e6c9a1da4097af58b05d41b0a964db7a17b9b6470c8cc8b49612954f573ff68f
      name: horizon_image_url_default
    - image: quay.io/podified-antelope-centos9/openstack-horizon@sha256:e6c9a1da4097af58b05d41b0a964db7a17b9b6470c8cc8b49612954f573ff68f
      name: horizon-image-url-default
  version: 0.0.1
  webhookdefinitions:
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: horizon-operator-controller-manager
      failurePolicy: Fail
      generateName: mhorizon.kb.io
      rules:
        - apiGroups:
            - horizon.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - horizons
      sideEffects: None
      targetPort: 9443
      type: MutatingAdmissionWebhook
      webhookPath: /mutate-horizon-openstack-org-v1beta1-horizon
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: horizon-operator-controller-manager
      failurePolicy: Fail
      generateName: vhorizon.kb.io
      rules:
        - apiGroups:
            - horizon.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - horizons
      sideEffects: None
      targetPort: 9443
      type: ValidatingAdmissionWebhook
      webhookPath: /validate-horizon-openstack-org-v1beta1-horizon
