apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mariadb.openstack.org/v1beta1",
          "kind": "Galera",
          "metadata": {
            "name": "openstack"
          },
          "spec": {
            "replicas": 3,
            "secret": "osp-secret",
            "storageClass": "local-storage",
            "storageRequest": "500M"
          }
        },
        {
          "apiVersion": "mariadb.openstack.org/v1beta1",
          "kind": "MariaDBAccount",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "mariadb-operator",
              "app.kubernetes.io/instance": "mariadbaccount-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "mariadbaccount",
              "app.kubernetes.io/part-of": "mariadb-operator",
              "mariaDBDatabaseName": "neutron"
            },
            "name": "neutron1"
          },
          "spec": {
            "secret": "neutrondb-secret",
            "userName": "neutron1"
          }
        },
        {
          "apiVersion": "mariadb.openstack.org/v1beta1",
          "kind": "MariaDBDatabase",
          "metadata": {
            "labels": {
              "dbName": "mariadb"
            },
            "name": "scott"
          },
          "spec": {
            "name": "scott",
            "secret": "tiger"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-24T13:13:52Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: mariadb-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Galera is the Schema for the galeras API
        displayName: Galera
        kind: Galera
        name: galeras.mariadb.openstack.org
        specDescriptors:
          - description: TLS settings for MySQL service and internal Galera replication
            displayName: TLS
            path: tls
        version: v1beta1
      - description: MariaDBAccount is the Schema for the mariadbaccounts API
        displayName: Maria DBAccount
        kind: MariaDBAccount
        name: mariadbaccounts.mariadb.openstack.org
        version: v1beta1
      - description: MariaDBDatabase is the Schema for the mariadbdatabases API
        displayName: Maria DBDatabase
        kind: MariaDBDatabase
        name: mariadbdatabases.mariadb.openstack.org
        version: v1beta1
  description: MariaDB Operator
  displayName: MariaDB Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets/status
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - endpoints
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - galeras
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - galeras/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - galeras/status
              verbs:
                - get
                - list
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - anyuid
              resources:
                - securitycontextconstraints
              verbs:
                - use
            - apiGroups:
                - topology.openstack.org
              resources:
                - topologies
              verbs:
                - get
                - list
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: mariadb-operator-controller-manager
      deployments:
        - label:
            control-plane: controller-manager
            openstack.org/operator-name: mariadb
          name: mariadb-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                openstack.org/operator-name: mariadb
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
                  openstack.org/operator-name: mariadb
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    env:
                      - name: RELATED_IMAGE_MARIADB_IMAGE_URL_DEFAULT
                        value: quay.io/podified-antelope-centos9/openstack-mariadb@sha256:57d3e9803f62938a1a0ea05f3948fe847f670f52c1b2388d287c940236b591c3
                    image: quay.io/openstack-k8s-operators/mariadb-operator@sha256:10f46784a706c5cd0e9a31ddb9713207abbc35df15baccf5d98696c1432c3dbb
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    ports:
                      - containerPort: 9443
                        name: webhook-server
                        protocol: TCP
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 256Mi
                      requests:
                        cpu: 10m
                        memory: 128Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                    volumeMounts:
                      - mountPath: /tmp/k8s-webhook-server/serving-certs
                        name: cert
                        readOnly: true
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: mariadb-operator-controller-manager
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: cert
                    secret:
                      defaultMode: 420
                      secretName: webhook-server-cert
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: mariadb-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - OpenStack
    - Identity
    - MariaDB
  links:
    - name: MariaDB Operator
      url: https://github.com/openstack-k8s-operators/mariadb-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  relatedImages:
    - image: quay.io/podified-antelope-centos9/openstack-mariadb@sha256:57d3e9803f62938a1a0ea05f3948fe847f670f52c1b2388d287c940236b591c3
      name: mariadb-image-url-default
    - image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
      name: kube-rbac-proxy
    - image: quay.io/openstack-k8s-operators/mariadb-operator@sha256:10f46784a706c5cd0e9a31ddb9713207abbc35df15baccf5d98696c1432c3dbb
      name: manager
    - image: quay.io/podified-antelope-centos9/openstack-mariadb@sha256:57d3e9803f62938a1a0ea05f3948fe847f670f52c1b2388d287c940236b591c3
      name: mariadb_image_url_default
  version: 0.0.1
  webhookdefinitions:
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: mariadb-operator-controller-manager
      failurePolicy: Fail
      generateName: mgalera.kb.io
      rules:
        - apiGroups:
            - mariadb.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - galeras
      sideEffects: None
      targetPort: 9443
      type: MutatingAdmissionWebhook
      webhookPath: /mutate-mariadb-openstack-org-v1beta1-galera
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: mariadb-operator-controller-manager
      failurePolicy: Fail
      generateName: vgalera.kb.io
      rules:
        - apiGroups:
            - mariadb.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - galeras
      sideEffects: None
      targetPort: 9443
      type: ValidatingAdmissionWebhook
      webhookPath: /validate-mariadb-openstack-org-v1beta1-galera
