apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "neutron.openstack.org/v1beta1",
          "kind": "NeutronAPI",
          "metadata": {
            "name": "neutron",
            "namespace": "openstack"
          },
          "spec": {
            "customServiceConfig": "[DEFAULT]\ndebug = true\n",
            "databaseAccount": "neutron",
            "databaseInstance": "openstack",
            "memcachedInstance": "memcached",
            "preserveJobs": false,
            "rabbitMqClusterName": "rabbitmq",
            "secret": "neutron-secret",
            "serviceUser": "neutron"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-06-05T08:18:30Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: neutron-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: NeutronAPI is the Schema for the neutronapis API
        displayName: Neutron API
        kind: NeutronAPI
        name: neutronapis.neutron.openstack.org
        specDescriptors:
          - description: TLS - Parameters related to the TLS
            displayName: TLS
            path: tls
          - description: API tls type which encapsulates for API services
            displayName: API
            path: tls.api
          - description: Ovn GenericService - holds the secret for the OvnDb client cert
            displayName: Ovn
            path: tls.ovn
        version: v1beta1
  description: Neutron Operator
  displayName: Neutron Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - k8s.cni.cncf.io
              resources:
                - network-attachment-definitions
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneapis
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneendpoints
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneservices
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - memcached.openstack.org
              resources:
                - memcacheds
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - neutron.openstack.org
              resources:
                - neutronapis
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - neutron.openstack.org
              resources:
                - neutronapis/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - neutron.openstack.org
              resources:
                - neutronapis/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - ovn.openstack.org
              resources:
                - ovndbclusters
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rabbitmq.openstack.org
              resources:
                - transporturls
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - anyuid
              resources:
                - securitycontextconstraints
              verbs:
                - use
            - apiGroups:
                - topology.openstack.org
              resources:
                - topologies
              verbs:
                - get
                - list
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: neutron-operator-controller-manager
      deployments:
        - label:
            control-plane: controller-manager
            openstack.org/operator-name: neutron
          name: neutron-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                openstack.org/operator-name: neutron
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
                  openstack.org/operator-name: neutron
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    env:
                      - name: RELATED_IMAGE_NEUTRON_API_IMAGE_URL_DEFAULT
                        value: quay.io/podified-antelope-centos9/openstack-neutron-server@sha256:2192d902f7eb951bc5e7774596f6484e1311deccda22d85b5926956ab9909ca3
                    image: quay.io/openstack-k8s-operators/neutron-operator@sha256:da08b3c2e379399cdab66cf8c5248ed8bf9783745cf4d68a6c9efb0c30838a0a
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    ports:
                      - containerPort: 9443
                        name: webhook-server
                        protocol: TCP
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 256Mi
                      requests:
                        cpu: 10m
                        memory: 128Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                    volumeMounts:
                      - mountPath: /tmp/k8s-webhook-server/serving-certs
                        name: cert
                        readOnly: true
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: neutron-operator-controller-manager
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: cert
                    secret:
                      defaultMode: 420
                      secretName: webhook-server-cert
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: neutron-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - OpenStack
    - Network
    - Neutron
  links:
    - name: Neutron Operator
      url: https://github.com/openstack-k8s-operators/neutron-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  relatedImages:
    - image: quay.io/podified-antelope-centos9/openstack-neutron-server@sha256:2192d902f7eb951bc5e7774596f6484e1311deccda22d85b5926956ab9909ca3
      name: neutron_api_image_url_default
    - image: quay.io/podified-antelope-centos9/openstack-neutron-server@sha256:2192d902f7eb951bc5e7774596f6484e1311deccda22d85b5926956ab9909ca3
      name: neutron-api-image-url-default
    - image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
      name: kube-rbac-proxy
    - image: quay.io/openstack-k8s-operators/neutron-operator@sha256:da08b3c2e379399cdab66cf8c5248ed8bf9783745cf4d68a6c9efb0c30838a0a
      name: manager
  version: 0.0.1
  webhookdefinitions:
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: neutron-operator-controller-manager
      failurePolicy: Fail
      generateName: mneutronapi.kb.io
      rules:
        - apiGroups:
            - neutron.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - neutronapis
      sideEffects: None
      targetPort: 9443
      type: MutatingAdmissionWebhook
      webhookPath: /mutate-neutron-openstack-org-v1beta1-neutronapi
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: neutron-operator-controller-manager
      failurePolicy: Fail
      generateName: vneutronapi.kb.io
      rules:
        - apiGroups:
            - neutron.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - neutronapis
      sideEffects: None
      targetPort: 9443
      type: ValidatingAdmissionWebhook
      webhookPath: /validate-neutron-openstack-org-v1beta1-neutronapi
