apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "placement.openstack.org/v1beta1",
          "kind": "PlacementAPI",
          "metadata": {
            "name": "placement"
          },
          "spec": {
            "customServiceConfig": "[DEFAULT]\ndebug = true\n",
            "databaseAccount": "placement",
            "databaseInstance": "openstack",
            "preserveJobs": false,
            "replicas": 1,
            "secret": "placement-secret",
            "serviceUser": "placement"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-06-04T16:28:52Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: placement-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: PlacementAPI is the Schema for the placementapis API
        displayName: Placement API
        kind: PlacementAPI
        name: placementapis.placement.openstack.org
        specDescriptors:
          - description: TLS - Parameters related to the TLS
            displayName: TLS
            path: tls
        version: v1beta1
  description: Placement Operator
  displayName: Placement Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - k8s.cni.cncf.io
              resources:
                - network-attachment-definitions
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneapis
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneendpoints
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - keystone.openstack.org
              resources:
                - keystoneservices
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbaccounts/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mariadb.openstack.org
              resources:
                - mariadbdatabases/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - placement.openstack.org
              resources:
                - placementapis
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - placement.openstack.org
              resources:
                - placementapis/finalizers
              verbs:
                - patch
                - update
            - apiGroups:
                - placement.openstack.org
              resources:
                - placementapis/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - anyuid
              resources:
                - securitycontextconstraints
              verbs:
                - use
            - apiGroups:
                - topology.openstack.org
              resources:
                - topologies
              verbs:
                - get
                - list
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: placement-operator-controller-manager
      deployments:
        - label:
            control-plane: controller-manager
            openstack.org/operator-name: placement
          name: placement-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                openstack.org/operator-name: placement
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
                  openstack.org/operator-name: placement
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --leader-elect
                    command:
                      - /manager
                    env:
                      - name: RELATED_IMAGE_PLACEMENT_API_IMAGE_URL_DEFAULT
                        value: quay.io/podified-antelope-centos9/openstack-placement-api@sha256:c7bff310380980ca3ed9c5c7fd5fb334aeb8cbd760096f2adce05638790e9d21
                    image: quay.io/openstack-k8s-operators/placement-operator@sha256:0e9cc04d1421ac129bbae99f4e8089a41cd6dcb768f3fbc14264a1b5968d8b60
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    ports:
                      - containerPort: 9443
                        name: webhook-server
                        protocol: TCP
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 256Mi
                      requests:
                        cpu: 10m
                        memory: 128Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                    volumeMounts:
                      - mountPath: /tmp/k8s-webhook-server/serving-certs
                        name: cert
                        readOnly: true
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: placement-operator-controller-manager
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: cert
                    secret:
                      defaultMode: 420
                      secretName: webhook-server-cert
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: placement-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - OpenStack
    - Placement
  links:
    - name: Placement Operator
      url: https://github.com/openstack-k8s-operators/placement-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  relatedImages:
    - image: quay.io/podified-antelope-centos9/openstack-placement-api@sha256:c7bff310380980ca3ed9c5c7fd5fb334aeb8cbd760096f2adce05638790e9d21
      name: placement-api-image-url-default
    - image: quay.io/openstack-k8s-operators/kube-rbac-proxy@sha256:d28df2924a366ed857d6c2c14baac9741238032d41f3d02c12cd757189b68b8a
      name: kube-rbac-proxy
    - image: quay.io/openstack-k8s-operators/placement-operator@sha256:0e9cc04d1421ac129bbae99f4e8089a41cd6dcb768f3fbc14264a1b5968d8b60
      name: manager
    - image: quay.io/podified-antelope-centos9/openstack-placement-api@sha256:c7bff310380980ca3ed9c5c7fd5fb334aeb8cbd760096f2adce05638790e9d21
      name: placement_api_image_url_default
  version: 0.0.1
  webhookdefinitions:
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: placement-operator-controller-manager
      failurePolicy: Fail
      generateName: mplacementapi.kb.io
      rules:
        - apiGroups:
            - placement.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - placementapis
      sideEffects: None
      targetPort: 9443
      type: MutatingAdmissionWebhook
      webhookPath: /mutate-placement-openstack-org-v1beta1-placementapi
    - admissionReviewVersions:
        - v1
      containerPort: 443
      deploymentName: placement-operator-controller-manager
      failurePolicy: Fail
      generateName: vplacementapi.kb.io
      rules:
        - apiGroups:
            - placement.openstack.org
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - placementapis
      sideEffects: None
      targetPort: 9443
      type: ValidatingAdmissionWebhook
      webhookPath: /validate-placement-openstack-org-v1beta1-placementapi
