apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rabbitmq.com/v1beta1",
          "kind": "RabbitmqCluster",
          "metadata": {
            "name": "sample",
            "namespace": "rabbitmq-system"
          },
          "spec": {
            "replicas": 1,
            "service": {
              "type": "LoadBalancer"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-10-17T17:39:35Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: rabbitmq-cluster-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: RabbitmqCluster is the Schema for the RabbitmqCluster API. Each instance of this object corresponds to a single RabbitMQ cluster.
        displayName: Rabbitmq Cluster
        kind: RabbitmqCluster
        name: rabbitmqclusters.rabbitmq.com
        version: v1beta1
  description: RabbitMQ Cluster Operator
  displayName: RabbitMQ Cluster Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - endpoints
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - get
                - patch
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - update
                - watch
            - apiGroups:
                - rabbitmq.com
              resources:
                - rabbitmqclusters
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - rabbitmq.com
              resources:
                - rabbitmqclusters/finalizers
              verbs:
                - update
            - apiGroups:
                - rabbitmq.com
              resources:
                - rabbitmqclusters/status
              verbs:
                - get
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - get
                - list
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - create
                - get
                - list
                - update
                - watch
          serviceAccountName: rabbitmq-cluster-operator
      deployments:
        - label:
            app.kubernetes.io/component: rabbitmq-operator
            app.kubernetes.io/name: rabbitmq-cluster-operator
            app.kubernetes.io/part-of: rabbitmq
          name: rabbitmq-cluster-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: rabbitmq-cluster-operator
            strategy: {}
            template:
              metadata:
                labels:
                  app.kubernetes.io/component: rabbitmq-operator
                  app.kubernetes.io/name: rabbitmq-cluster-operator
                  app.kubernetes.io/part-of: rabbitmq
              spec:
                containers:
                  - command:
                      - /manager
                    env:
                      - name: OPERATOR_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    image: quay.io/openstack-k8s-operators/rabbitmq-cluster-operator@sha256:225524223bf2a7f3a4ce95958fc9ca6fdab02745fb70374e8ff5bf1ddaceda4b
                    name: operator
                    ports:
                      - containerPort: 9782
                        name: metrics
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 200m
                        memory: 500Mi
                      requests:
                        cpu: 200m
                        memory: 500Mi
                serviceAccountName: rabbitmq-cluster-operator
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
          serviceAccountName: rabbitmq-cluster-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - rabbitmq
  links:
    - name: Cluster Operator
      url: https://github.com/rabbitmq/cluster-operator
  maturity: alpha
  provider:
    name: RabbitMQ
    url: https://rabbitmq.com
  relatedImages:
    - image: quay.io/openstack-k8s-operators/rabbitmq-cluster-operator@sha256:225524223bf2a7f3a4ce95958fc9ca6fdab02745fb70374e8ff5bf1ddaceda4b
      name: operator
  version: 0.0.1
