apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: swift-operator-swift-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swift-operator-swift-role
subjects:
- kind: ServiceAccount
  name: swift-operator-swift
  namespace: openstack
- kind: ServiceAccount
  name: swift
  namespace: openstack
